name: suika-linux
on:
  push:
  pull_request:
jobs:
  android:
    runs-on: "ubuntu-22.04"
    name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt install -y build-essential libasound2-dev libx11-dev libxpm-dev mesa-common-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          cd build/linux-x86_64
          ./build-libs.sh
          make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika-linux-x86_64
          path: build/linux-x86_64/suika
