name: suika-web
on:
  push:
  pull_request:
jobs:
  emscripten:
    runs-on: "ubuntu-22.04"
    name: web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: Build
        run: |
          cd build/emscripten
          make
          tar czf web.tar.gz html
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika-web.tar.gz
          path: build/emscripten/web.tar.gz
