name: suika-android
on:
  push:
  pull_request:
jobs:
  android:
    runs-on: "ubuntu-22.04"
    name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          cd build/android
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          export ANDROID_SDK_ROOT=`pwd`/cmdline-tools
          yes | ./cmdline-tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT
          ./cmdline-tools/bin/sdkmanager "platforms;android-30" --sdk_root=$ANDROID_SDK_ROOT
          ./prepare-libs.sh
          ./gradlew build --stacktrace
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika.apk
          path: build/android/app/build/outputs/apk/debug/app-debug.apk
