name: suika-linux
on:
  push:
  pull_request:
jobs:
  android:
    runs-on: "ubuntu-22.04"
    name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt-get install -y build-essential
          sudo apt-get install -y libasound2-dev
          sudo apt-get install -y libx11-dev 
          sudo apt-get install -y libxpm-dev 
          sudo apt-get install -y mesa-common-dev 
          sudo apt-get install -y libgstreamer1.0-dev 
          sudo apt-get install -y libgstreamer-plugins-base1.0-dev
          cd build/linux-x86_64
          ./build-libs.sh
          make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika-linux-x86_64
          path: build/linux-x86_64/suika
